name: Update README
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: update-readme
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  update-readme:
    if: github.repository == 'hiteshnayak305/hiteshnayak305'
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-github-io:
    if: github.repository == 'hiteshnayak305/hiteshnayak305'
    needs: update-readme
    name: push master to github.io repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push master to hiteshnayak305.github.io
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PA_TOKEN }}
          repository: hiteshnayak305/hiteshnayak305.github.io
          branch: master
